Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace WeatherAPI.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }

        public DbSet<Weather> Weather { get; set; }
        public DbSet<Token.Token> Tokens { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace WeatherAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Weather.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WeatherAPI.Models
{
    public class Weather
    {
        [Key] public Guid Id { get; set; }
        public int Humidity { get; set; }
        public int Temperature { get; set; }
        public int MinTemperature { get; set; }
        public int MaxTemperature { get; set; }
    }
}

Models/WeatherViewModel.cs
using Newtonsoft.Json;

namespace WeatherAPI.Models
{
    public class WeatherViewModel
    {
        [JsonProperty("humidity")] public int Humidity { get; set; }

        [JsonProperty("temperature")] public int Temperature { get; set; }

        [JsonProperty("min_temperature")] public int MinTemperature { get; set; }

        [JsonProperty("max_temperature")] public int MaxTemperature { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using WeatherAPI.Models;

namespace WeatherAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/WeathersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WeatherAPI.Filters;
using WeatherAPI.Models;

namespace WeatherAPI.Controllers
{
    public class WeathersController : Controller
    {
        private readonly AppDbContext _context;

        [AuthenticationFilter]
        public WeathersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Weathers
        public async Task<IActionResult> Index()
        {
            var newWeather = new Weather();
            var weatherModel = new List<Weather>();
            var w = FromApi();
            newWeather.Id = new Guid();
            newWeather.Humidity = w.Humidity;
            newWeather.Temperature = w.Temperature;
            newWeather.MinTemperature = w.MinTemperature;
            newWeather.MaxTemperature = w.MaxTemperature;
            weatherModel.Add(newWeather);
            weatherModel.AddRange(await _context.Weather.ToListAsync());
            return View(weatherModel);
        }

        public WeatherViewModel FromApi()
        {
            var weather = new WeatherViewModel();
            try
            {
                var w = new WeatherViewModel();
                var httpClient1 = new HttpClient();
                var apiUrl = "http://demo4567044.mockable.io/";
                httpClient1.BaseAddress = new Uri(apiUrl);
                var response = httpClient1.GetAsync("weather").Result;
                if (response.IsSuccessStatusCode)
                {
                    var message = response.Content.ReadAsStringAsync().Result;
                    weather = JsonConvert.DeserializeObject<WeatherViewModel>(message);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return weather;
        }

        // GET: Weathers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null) return NotFound();

            var weather = await _context.Weather
                .FirstOrDefaultAsync(m => m.Id == id);
            if (weather == null) return NotFound();

            return View(weather);
        }

        // GET: Weathers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Weathers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Humidity,Temperature,MinTemperature,MaxTemperature")]
            Weather weather)
        {
            if (ModelState.IsValid)
            {
                weather.Id = Guid.NewGuid();
                _context.Add(weather);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(weather);
        }

        // GET: Weathers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return NotFound();

            var weather = await _context.Weather.FindAsync(id);
            if (weather == null) return NotFound();
            return View(weather);
        }

        // POST: Weathers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id,
            [Bind("Id,Humidity,Temperature,MinTemperature,MaxTemperature")]
            Weather weather)
        {
            if (id != weather.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(weather);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WeatherExists(weather.Id))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(weather);
        }

        // GET: Weathers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return NotFound();

            var weather = await _context.Weather
                .FirstOrDefaultAsync(m => m.Id == id);
            if (weather == null) return NotFound();

            return View(weather);
        }

        // POST: Weathers/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var weather = await _context.Weather.FindAsync(id);
            _context.Weather.Remove(weather);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WeatherExists(Guid id)
        {
            return _context.Weather.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WeatherAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeatherAPI</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Weathers" asp-action="Index">Weather</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - WeatherAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>

Views/Weathers/Create.cshtml
@model WeatherAPI.Models.Weather

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Weather</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Humidity" class="control-label"></label>
                <input asp-for="Humidity" class="form-control"/>
                <span asp-validation-for="Humidity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Temperature" class="control-label"></label>
                <input asp-for="Temperature" class="form-control"/>
                <span asp-validation-for="Temperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinTemperature" class="control-label"></label>
                <input asp-for="MinTemperature" class="form-control"/>
                <span asp-validation-for="MinTemperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxTemperature" class="control-label"></label>
                <input asp-for="MaxTemperature" class="form-control"/>
                <span asp-validation-for="MaxTemperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/Weathers/Delete.cshtml
@model WeatherAPI.Models.Weather

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Weather</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Humidity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Humidity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Temperature)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Temperature)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MinTemperature)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MinTemperature)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MaxTemperature)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MaxTemperature)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Weathers/Details.cshtml
@model WeatherAPI.Models.Weather

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Weather</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Humidity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Humidity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Temperature)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Temperature)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MinTemperature)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MinTemperature)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MaxTemperature)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MaxTemperature)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Weathers/Edit.cshtml
@model WeatherAPI.Models.Weather

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Weather</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Humidity" class="control-label"></label>
                <input asp-for="Humidity" class="form-control"/>
                <span asp-validation-for="Humidity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Temperature" class="control-label"></label>
                <input asp-for="Temperature" class="form-control"/>
                <span asp-validation-for="Temperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinTemperature" class="control-label"></label>
                <input asp-for="MinTemperature" class="form-control"/>
                <span asp-validation-for="MinTemperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxTemperature" class="control-label"></label>
                <input asp-for="MaxTemperature" class="form-control"/>
                <span asp-validation-for="MaxTemperature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/Weathers/Index.cshtml
@model IEnumerable<WeatherAPI.Models.Weather>

@{
    ViewData["Title"] = "Index";
}

@Html.AntiForgeryToken();


<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Humidity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Temperature)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MinTemperature)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxTemperature)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Humidity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Temperature)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MinTemperature)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxTemperature)
            </td>
            <td>
                <div @item.Id !=null>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>